# Generated by Django 6.0.3 on 2026-04-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.architectquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_installation_id', models.BigIntegerField(blank=True, null=True)),
                ('github_repo_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('guarantee_date', models.DateField()),
                ('is_detailed', models.BooleanField(default=False)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='users.team')),
            ],
        ),
        migrations.AddField(
            model_name='architectquestion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.project'),
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_policy', models.CharField(choices=[('hard_block', 'Hard block — revert silently'), ('soft_warn', 'Soft warn — revert with warning notification'), ('shame_block', 'Shame block — revert and post to webhook')], default='hard_block', max_length=20)),
                ('suggestion_policy', models.CharField(choices=[('auto', 'Auto-mark done immediately'), ('suggest', 'Notify developer to confirm'), ('review', 'Move to done, flag for leader review')], default='suggest', max_length=20)),
                ('shame_policy', models.CharField(choices=[('shame', 'Shame developer'), ('remind', 'Remind developer'), ('none', 'Do nothing')], default='remind', max_length=20)),
                ('skip_ai_completion_check', models.BooleanField(default=False)),
                ('max_commits_for_review', models.PositiveIntegerField(default=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], max_length=20)),
                ('importance', models.IntegerField(default=0)),
                ('phase_label', models.CharField(max_length=100)),
                ('blocked_tasks_count', models.PositiveIntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocked_tasks', to='projects.task')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to='users.developer')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done')], max_length=20)),
                ('to_status', models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
