# Generated by Django 6.0.3 on 2026-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='panic_policy',
            field=models.CharField(choices=[('force_archive', 'Forcefully archive low priority tasks'), ('delay_deadline', 'Delay deadline to avoid panic'), ('ask_leader_archive', 'Ask leader to review, force archive on timeout'), ('ask_leader_review', 'Ask leader to review, delay deadline on timeout'), ('ask_leader', 'Ask leader to review, do nothing on timeout'), ('none', 'Do nothing')], default='force_archive', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectsettings',
            name='shame_policy',
            field=models.CharField(choices=[('shame', 'Shame developer'), ('remind', 'Remind developer'), ('none', 'Do nothing')], default='shame', max_length=20),
        ),
    ]
