# Generated by Django 6.0.3 on 2026-04-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_installation_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_suggested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_policy', models.CharField(choices=[('hard_block', 'Hard block — revert silently'), ('soft_warn', 'Soft warn — revert with warning notification'), ('shame_block', 'Shame block — revert and post to webhook')], default='hard_block', max_length=20)),
                ('suggestion_policy', models.CharField(choices=[('auto', 'Auto-mark done immediately'), ('suggest', 'Notify developer to confirm'), ('review', 'Move to done, flag for leader review')], default='suggest', max_length=20)),
                ('skip_ai_completion_check', models.BooleanField(default=False)),
                ('max_commits_for_review', models.PositiveIntegerField(default=10)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='projects.project')),
            ],
        ),
    ]
