# Generated by Django 6.0.3 on 2026-04-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_tasks_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
