# Generated by Django 6.0.2 on 2026-03-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_task_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done')], max_length=20)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.task')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
