# Generated by Django 6.0.3 on 2026-04-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_repair_missing_github_link_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ai_suggested',
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='shame_policy',
            field=models.CharField(choices=[('shame', 'Shame developer'), ('remind', 'Remind developer'), ('none', 'Do nothing')], default='remind', max_length=20),
        ),
    ]
