# Generated by Django 6.0.2 on 2026-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_taskhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskhistory',
            old_name='old_status',
            new_name='from_status',
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='to_status',
            field=models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], default='archived', max_length=20),
            preserve_default=False,
        ),
    ]
