# Generated by Django 6.0.3 on 2026-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_task_ai_suggested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
