# Generated by Django 6.0.2 on 2026-03-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_old_status_taskhistory_from_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='guarantee_date',
            new_name='created_on',
        ),
    ]
