# Generated by Django 6.0.2 on 2026-03-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_guarantee_date_project_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guarantee_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
