# Generated by Django 6.0.2 on 2026-03-04 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_guarantee_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guarantee_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 24, 0, 0)),
            preserve_default=False,
        ),
    ]
