# Generated by Django 6.0.2 on 2026-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_guarantee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(default='acer', max_length=100),
            preserve_default=False,
        ),
    ]
