# Generated by Django 6.0.2 on 2026-03-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_task_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.JSONField(default={'acer': ['Django', 'REST', 'Deploment'], 'gopi': ['AI', 'Django'], 'sehal': ['kotlin', 'javascript']}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_tasks', to='projects.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default='pmepm', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'To-Do'), ('doing', 'Doing'), ('done', 'Done'), ('archived', 'Archived')], max_length=20),
        ),
    ]
