# Generated by Django 6.0.2 on 2026-03-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_team_task_depends_on_task_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocked_tasks', to='projects.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.task'),
        ),
    ]
