# Generated by Django 6.0.3 on 2026-03-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_task_depends_on_alter_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='question_round',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'slug')},
        ),
        migrations.CreateModel(
            name='ArchitectQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.architectquestion')),
            ],
        ),
    ]
