# Generated by Django 6.0.3 on 2026-03-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_question_round_alter_task_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='question_round',
        ),
        migrations.AddField(
            model_name='project',
            name='is_detailed',
            field=models.BooleanField(default=False),
        ),
    ]
