# Generated by Django 6.0.3 on 2026-04-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_UPDATE_SITE_NAME'),
        ('projects', '0002_project_github_installation_id_task_ai_suggested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.task')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('task', 'sha')},
            },
        ),
        migrations.CreateModel(
            name='UnrelatedCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('author', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('files_changed', models.JSONField(default=list)),
                ('lines_added', models.IntegerField(default=0)),
                ('lines_deleted', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unrelated_commits', to='Users.developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unrelated_commits', to='projects.project')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('project', 'sha')},
            },
        ),
    ]
