# Generated by Django 6.0.3 on 2026-04-22 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordBotIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_bot_integration', to='projects.project')),
                ('discord_guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_integrations', to='bot_integrations.discordguild')),
            ],
        ),
        migrations.DeleteModel(
            name='BotIntegration',
        ),
    ]
