# Generated by Django 6.0.3 on 2026-04-22 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0002_discordguild_discordbotintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('bot_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bot_integrations.discordbotintegration')),
            ],
        ),
    ]
