# Generated by Django 6.0.3 on 2026-04-22 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0003_notification'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projects', models.ManyToManyField(related_name='unfinished_discord_installations', to='projects.project')),
            ],
        ),
    ]
