# Generated by Django 6.0.3 on 2026-04-23 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0004_installationstate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationstate',
            name='projects',
        ),
        migrations.AddField(
            model_name='installationstate',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_states', to='bot_integrations.discordguild'),
        ),
    ]
