# Generated by Django 6.0.3 on 2026-04-23 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0005_remove_installationstate_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstate',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_states', to='bot_integrations.discordguild'),
        ),
    ]
