# Generated by Django 6.0.3 on 2026-04-24 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0006_alter_installationstate_guild'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_hour', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(23)])),
                ('scheduled_day_of_week', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('processed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cron_schedule', to='projects.project')),
            ],
        ),
    ]
