# Generated by Django 6.0.3 on 2026-04-24 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0007_cronschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronschedule',
            name='scheduled_day_of_week',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
