# Generated by Django 6.0.3 on 2026-04-26 09:11

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0008_alter_cronschedule_scheduled_day_of_week'),
        ('projects', '0002_projectsettings_panic_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('cut_tasks', 'Cut Tasks'), ('delay_deadline', 'Delay Deadline')], max_length=20, null=True)),
                ('timeout_time', models.DateTimeField(default=datetime.datetime(2026, 4, 26, 15, 11, 52, 2294, tzinfo=datetime.timezone.utc))),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(blank=True, choices=[('cut_tasks', 'Cut Tasks'), ('delay_deadline', 'Delay Deadline')], max_length=20, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('panic_recommendations', models.JSONField(blank=True, default=list, null=True)),
                ('deadline_update', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bot_integrations.notification')),
                ('timeout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='bot_integrations.timeout')),
            ],
        ),
    ]
