# Generated by Django 6.0.3 on 2026-04-26 13:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0009_timeout_notificationaction'),
        ('projects', '0002_projectsettings_panic_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeout',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='timeout_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 26, 19, 2, 58, 654453, tzinfo=datetime.timezone.utc)),
        ),
    ]
