# Generated by Django 6.0.3 on 2026-05-06 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0014_alter_timeout_timeout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeout',
            name='timeout_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 8, 30, 59, 561196, tzinfo=datetime.timezone.utc)),
        ),
    ]
