# Generated by Django 6.0.3 on 2026-05-06 02:33

import bot_integrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integrations', '0015_alter_timeout_timeout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeout',
            name='timeout_time',
            field=models.DateTimeField(default=bot_integrations.models._default_timeout),
        ),
    ]
