# Generated by Django 6.0.3 on 2026-04-11 13:18

from django.db import migrations
from django.conf import settings


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')

    SiteModel.objects.update_or_create(
        pk=1,  # ✅ HARD CODE
        defaults={
            'domain': 'scrumb.in',
            'name': 'Scrumb'
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
