# Generated by Django 6.0.3 on 2026-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_UPDATE_SITE_NAME'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
